<?php

namespace App;

use App\Profile;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    protected $guarded = ['id'];  
    
    protected $casts = [
        'created_at' => 'datetime:d-m-Y g:i A',
    ];
    
    public static function defaultPositions()
    {
        return [
            ['name'=>'PEMBANTU TADBIR','description'=>'pembantu tadbir'],
            ['name'=>'PEMBANTU OPERASI','description'=>'pembantu operasi'],
            ['name'=>'PEGAWAI PENERANGAN','description'=>'pegawai penerangan'],
            ['name'=>'PEMANDU KENDERAAN','description'=>'pemandu kenderaan'],
            ['name'=>'PEMBANTU PENERBITAN','description'=>'pembantu penerbitan'],
            ['name'=>'PENOLONG JURUTERA','description'=>'penolong jurutera'],
            ['name'=>'JURUTEKNIK','description'=>'juruteknik'],
            ['name'=>'PENGURUS ACARA','description'=>'pengurus acara'],
            ['name'=>'PEGAWAI KHIDMAT PELANGGAN (ONCC)','description'=>'pegawai khidmat pelanggan (oncc)'],
            ['name'=>'PEMBANTU TADBIR (KUP)','description'=>'pembantu tadbir (kup)'],
            ['name'=>'KETUA PEMBANTU TADBIR','description'=>'ketua pembantu tadbir'],
            ['name'=>'PEMBANTU TADBIR (N19)','description'=>'pembantu tadbir (n19)'],
            ['name'=>'PENOLONG PEGAWAI TEKNOLOGI MAKLUMAT','description'=>'penolong pegawai teknologi maklumat'],
            ['name'=>'PEGAWAI TADBIR','description'=>'pegawai tadbir'],
            ['name'=>'TIMBALAN SETIAUSAHA KERAJAAN (PENGURUSAN)','description'=>'timbalan setiausaha kerajaan (pengurusan)'],
            ['name'=>'PEMANDU','description'=>'pemandu'],
            ['name'=>'PENOLONG AKAUNTAN','description'=>'penolong akauntan'],
            ['name'=>'ARKITEK','description'=>'arkitek'],
            ['name'=>'PEMBANTU HAL EHWAL EKONOMI','description'=>'pembantu hal ehwal ekonomi'],
            ['name'=>'JURUFOTOGRAFI','description'=>'jurufotografi'],
            ['name'=>'PENOLONG PEGAWAI TADBIR','description'=>'penolong pegawai tadbir'],
            ['name'=>'PEGAWAI KHIDMAT PELANGGAN','description'=>'pegawai khidmat pelanggan'],
            ['name'=>'PEGAWAI BELIA DAN SUKAN','description'=>'pegawai belia dan sukan'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN','description'=>'penolong setiausaha kerajaan'],
            ['name'=>'PEMBANTU OPERASI (ONCC)','description'=>'pembantu operasi (oncc)'],
            ['name'=>'PENOLONG PEGAWAI BELIA DAN SUKAN','description'=>'penolong pegawai belia dan sukan'],
            ['name'=>'PEKERJA AWAM','description'=>'pekerja awam'],
            ['name'=>'PENOLONG PEGAWAI HAL EHWAL EKONOMI','description'=>'penolong pegawai hal ehwal ekonomi'],
            ['name'=>'PEMBANTU PENGUATKUASA','description'=>'pembantu penguatkuasa'],
            ['name'=>'AHLI MUZIK','description'=>'ahli muzik'],
            ['name'=>'PEMBANTU TADBIR (PERKERANIAN/OPERASI)','description'=>'pembantu tadbir (perkeranian/operasi)'],
            ['name'=>'PEGAWAI KHIDMAT PELANGGAN N19','description'=>'pegawai khidmat pelanggan n19'],
            ['name'=>'PEREKA','description'=>'pereka'],
            ['name'=>'PEGAWAI KOMUNIKASI STRATEGIK & MEDIA','description'=>'pegawai komunikasi strategik & media'],
            ['name'=>'PEMBANTU AWAM','description'=>'pembantu awam'],
            ['name'=>'TIMBALAN PENGARAH (PENTADBIRAN)','description'=>'timbalan pengarah (pentadbiran)'],
            ['name'=>'ARKITEK LANDSKAP','description'=>'arkitek landskap'],
            ['name'=>'PENASIHAT AGAMA','description'=>'penasihat agama'],
            ['name'=>'KETUA PEMBANTU TADBIR (W)','description'=>'ketua pembantu tadbir (w)'],
            ['name'=>'PEMBANTU TADBIR (W)','description'=>'pembantu tadbir (w)'],
            ['name'=>'PEMBANTU TADBIR KEWANGAN','description'=>'pembantu tadbir kewangan'],
            ['name'=>'PENOLONG PEGAWAI TADBIR KANAN','description'=>'penolong pegawai tadbir kanan'],
            ['name'=>'PENGURUS BESAR','description'=>'pengurus besar'],
            ['name'=>'PEMBANTU TADBIR ((PERKERANIAN/OPERASI)','description'=>'pembantu tadbir ((perkeranian/operasi)'],
            ['name'=>'PEGAWAI TEKNOLOGI MAKLUMAT','description'=>'pegawai teknologi maklumat'],
            ['name'=>'JURUTEKNIK KOMPUTER','description'=>'juruteknik komputer'],
            ['name'=>'ARTIS BUDAYA','description'=>'artis budaya'],
            ['name'=>'PENOLONG JURUTERA (AWAM)','description'=>'penolong jurutera (awam)'],
            ['name'=>'SETIAUSAHA PEJABAT','description'=>'setiausaha pejabat'],
            ['name'=>'PEGAWAI PERHUBUNGAN','description'=>'pegawai perhubungan'],
            ['name'=>'PEGAWAI PERHUBUNGAN AWAM','description'=>'pegawai perhubungan awam'],
            ['name'=>'PENOLONG PEGAWAI TEKNOLOGI MAKLUMAT (KUP)','description'=>'penolong pegawai teknologi maklumat (kup)'],
            ['name'=>'PEGAWAI TEKNOLOGI MAKLUMAT KANAN','description'=>'pegawai teknologi maklumat kanan'],
            ['name'=>'KETUA PENOLONG SETIAUSAHA KANAN KERAJAAN','description'=>'ketua penolong setiausaha kanan kerajaan'],
            ['name'=>'PENOLONG PEGAWAI PSIKOLOGI','description'=>'penolong pegawai psikologi'],
            ['name'=>'KETUA PENOLONG PEGAWAI BELIA DAN SUKAN','description'=>'ketua penolong pegawai belia dan sukan'],
            ['name'=>'PEMBANTU TADBIR (P/O)','description'=>'pembantu tadbir (p/o)'],
            ['name'=>'PENGARAH','description'=>'pengarah'],
            ['name'=>'PENGURUS PERHUBUNGAN AWAM','description'=>'pengurus perhubungan awam'],
            ['name'=>'TIMBALAN SETIAUSAHA KERAJAAN (PEMBANGUNAN)','description'=>'timbalan setiausaha kerajaan (pembangunan)'],
            ['name'=>'PENOLONG JURUTERA (ELEKTRIK)','description'=>'penolong jurutera (elektrik)'],
            ['name'=>'PENYELIA PUSAT PANGGILAN SETEMPAT N.MELAKA (ONCC)','description'=>'penyelia pusat panggilan setempat n.melaka (oncc)'],
            ['name'=>'PENGURUS PENGAUDITAN PELANCONGAN','description'=>'pengurus pengauditan pelancongan'],
            ['name'=>'PENOLONG PENGARAH','description'=>'penolong pengarah'],
            ['name'=>'KETUA PENOLONG SETIAUSAHA KERAJAAN','description'=>'ketua penolong setiausaha kerajaan'],
            ['name'=>'PEMBANTU AM PEJABAT','description'=>'pembantu am pejabat'],
            ['name'=>'SETIAUSAHA BAHAGIAN','description'=>'setiausaha bahagian'],
            ['name'=>'PENOLONG PEGAWAI TADBIR TERTINGGI','description'=>'penolong pegawai tadbir tertinggi'],
            ['name'=>'PENOLONG PEGAWAI PERANCANG DAN DESA','description'=>'penolong pegawai perancang dan desa'],
            ['name'=>'JURUTERA','description'=>'jurutera'],
            ['name'=>'PEMBANTU TADBIR (PERKERANIAN/ OPERASI)','description'=>'pembantu tadbir (perkeranian/ operasi)'],
            ['name'=>'PENOLONG JURUUKUR BAHAN','description'=>'penolong juruukur bahan'],
            ['name'=>'PEREKA TARI','description'=>'pereka tari'],
            ['name'=>'KETUA PEGAWAI EKSEKUTIF','description'=>'ketua pegawai eksekutif'],
            ['name'=>'PENOLONG JURUTERA KANAN','description'=>'penolong jurutera kanan'],
            ['name'=>'PENOLONG PEGAWAI UNDANG-UNDANG','description'=>'penolong pegawai undang-undang'],
            ['name'=>'PEMBANTU TADBIR N19 (PSH)','description'=>'pembantu tadbir n19 (psh)'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN (KUALITI)','description'=>'penolong setiausaha kerajaan (kualiti)'],
            ['name'=>'KETUA PEMBANTU TADBIR','description'=>'ketua pembantu tadbir'],
            ['name'=>'TIMBALAN PENGARAH (TEKNIKAL)','description'=>'timbalan pengarah (teknikal)'],
            ['name'=>'KETUA BAHAGIAN','description'=>'ketua bahagian'],
            ['name'=>'PEMUZIK','description'=>'pemuzik'],
            ['name'=>'PEGAWAI EHWAL EKONOMI','description'=>'pegawai ehwal ekonomi'],
            ['name'=>'PENOLONG PEGAWAI TANAH','description'=>'penolong pegawai tanah'],
            ['name'=>'JURU AUDIO VISUAL','description'=>'juru audio visual'],
            ['name'=>'PEGAWAI KHIDMAT PELANGGAN (KUP N22)','description'=>'pegawai khidmat pelanggan (kup n22)'],
            ['name'=>'PEGAWAI KHAS II KEPADA YB SETIAUSAHA KERAJAAN NEGERI','description'=>'pegawai khas ii kepada yb setiausaha kerajaan negeri'],
            ['name'=>'PEGAWAI TADBIR DAN DIPLOMATIK','description'=>'pegawai tadbir dan diplomatik'],
            ['name'=>'PEGAWAI TADBIR (SERI BENDAHARA)','description'=>'pegawai tadbir (seri bendahara)'],
            ['name'=>'PENOLONG JURUAUDIT','description'=>'penolong juruaudit'],
            ['name'=>'PENOLONG PEGAWAI BELIA & SUKAN','description'=>'penolong pegawai belia & sukan'],
            ['name'=>'PEGAWAI PSIKOLOGI','description'=>'pegawai psikologi'],
            ['name'=>'PENGURUS PROMOSI','description'=>'pengurus promosi'],
            ['name'=>'JURUIRING PDRM','description'=>'juruiring pdrm'],
            ['name'=>'PENGURUS KEBUDAYAAN','description'=>'pengurus kebudayaan'],
            ['name'=>'PEMBANTU EHWAL EKONOMI','description'=>'pembantu ehwal ekonomi'],
            ['name'=>'SETIAUSAHA KHAS PERHUBUNGAN KEPADA YAB KETUA MENTERI MELAKA','description'=>'setiausaha khas perhubungan kepada yab ketua menteri melaka'],
            ['name'=>'PENGURUS KANAN','description'=>'pengurus kanan'],
            ['name'=>'SETIAUSAHA HAL EHWAL MASYARAKAT','description'=>'setiausaha hal ehwal masyarakat'],
            ['name'=>'PENOLONG PEGAWAI TEKNOLOGI MAKLUMAT (F29)','description'=>'penolong pegawai teknologi maklumat (f29)'],
            ['name'=>'KETUA PENOLONG PENGARAH','description'=>'ketua penolong pengarah'],
            ['name'=>'PENGURUS KEWANGAN','description'=>'pengurus kewangan'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN (MAJLIS)','description'=>'penolong setiausaha kerajaan (majlis)'],
            ['name'=>'PEMBANTU BELIA & SUKAN','description'=>'pembantu belia & sukan'],
            ['name'=>'PENOLONG JURU UKUR BAHAN','description'=>'penolong juru ukur bahan'],
            ['name'=>'PENOLONG PEGAWAI TADBIR (K)','description'=>'penolong pegawai tadbir (k)'],
            ['name'=>'PENOLONG PEGAWAI TADBIR','description'=>'penolong pegawai tadbir'],
            ['name'=>'ARTIS BUDAYA (PENYANYI)','description'=>'artis budaya (penyanyi)'],
            ['name'=>'PENGIRING RAPAT','description'=>'pengiring rapat'],
            ['name'=>'SETIAUSAHA SULIT KANAN KEPADA YAB KETUA MENTERI MELAKA','description'=>'setiausaha sulit kanan kepada yab ketua menteri melaka'],
            ['name'=>'SETIAUSAHA POLITIK KEPADA YAB KETUA MENTERI MELAKA','description'=>'setiausaha politik kepada yab ketua menteri melaka'],
            ['name'=>'PENASIHAT EKONOMI DAN INOVASI','description'=>'penasihat ekonomi dan inovasi'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN (D)','description'=>'penolong setiausaha kerajaan (d)'],
            ['name'=>'PENOLONG PEGAWAI TADBIR (T)','description'=>'penolong pegawai tadbir (t)'],
            ['name'=>'PEGAWAI TADBIR UNDANG-UNDANG','description'=>'pegawai tadbir undang-undang'],
            ['name'=>'JURUAUDIO VISUAL','description'=>'juruaudio visual'],
            ['name'=>'PENOLONG PEGAWAI TADBIR TINGGI','description'=>'penolong pegawai tadbir tinggi'],
            ['name'=>'AKAUNTAN','description'=>'akauntan'],
            ['name'=>'PENOLONG PEGAWAI TADBIR(N27)','description'=>'penolong pegawai tadbir(n27)'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN (PENTADBIRAN)','description'=>'penolong setiausaha kerajaan (pentadbiran)'],
            ['name'=>'PEMBANTU TADBIR (KEWANGAN)','description'=>'pembantu tadbir (kewangan)'],
            ['name'=>'PEGAWAI MEDIA','description'=>'pegawai media'],
            ['name'=>'PEMBANTU MAKMAL','description'=>'pembantu makmal'],
            ['name'=>'PEGAWAI KHAS','description'=>'pegawai khas'],
            ['name'=>'KETUA PEMBANTU TADBIR TERTINGGI','description'=>'ketua pembantu tadbir tertinggi'],
            ['name'=>'KETUA PEMUZIK','description'=>'ketua pemuzik'],
            ['name'=>'KETUA UNIT','description'=>'ketua unit'],
            ['name'=>'PEGAWAI SAINS','description'=>'pegawai sains'],
            ['name'=>'PENOLONG PEGAWAI PENERBITAN','description'=>'penolong pegawai penerbitan'],
            ['name'=>'PENULIS TEKS UCAPAN','description'=>'penulis teks ucapan'],
            ['name'=>'PENOLONG PEGAWAI PERANCANG BANDAR DAN DESA','description'=>'penolong pegawai perancang bandar dan desa'],
            ['name'=>'PEMBANTU TADBIR (MEMANGKU N22)','description'=>'pembantu tadbir (memangku n22)'],
            ['name'=>'SETIAUSAHA KHAS HAL EHWAL MASYARAKAT','description'=>'setiausaha khas hal ehwal masyarakat'],
            ['name'=>'PENGURUS PEMASARAN','description'=>'pengurus pemasaran'],
            ['name'=>'PENOLONG SETIAUSAHA KERAJAAN NEGERI','description'=>'penolong setiausaha kerajaan negeri'],
            ['name'=>'PENOLONG PENGURUS KEBUDAYAAN','description'=>'penolong pengurus kebudayaan'],
            ['name'=>'KETUA ICT NEGERI','description'=>'ketua ict negeri'],
            ['name'=>'PENGUASA KANAN','description'=>'penguasa kanan'],
            ['name'=>'PEGAWAI KHAS KEPADA YB SETIAUSAHA KERAJAAN NEGERI','description'=>'pegawai khas kepada yb setiausaha kerajaan negeri'],
            ['name'=>'TIMBALAN KETUA PEGAWAI EKSEKUTIF','description'=>'timbalan ketua pegawai eksekutif'],
            ['name'=>'KETUA PEMBANTU TADBIR (PERKERANIAN/OPERASI)','description'=>'ketua pembantu tadbir (perkeranian/operasi)'],
            ['name'=>'PEGAWAI PERANCANG BANDAR DAN DESA','description'=>'pegawai perancang bandar dan desa'],
            ['name'=>'PENYANYI','description'=>'penyanyi'],
            ['name'=>'SETIAUSAHA KERAJAAN NEGERI','description'=>'setiausaha kerajaan negeri'],
            ['name'=>'PEGAWAI PERANCANG BANDAR & DESA','description'=>'pegawai perancang bandar & desa'],
            ['name'=>'PEMBANTU TADBIR (STOR)','description'=>'pembantu tadbir (stor)'],
            ['name'=>'PENGHANTAR NOTIS','description'=>'penghantar notis'],
            ['name'=>'PENGARAH PUSAT SUMBER','description'=>'pengarah pusat sumber'],
            ['name'=>'SETIAUSAHA SULIT KEPADA YAB KETUA MENTERI','description'=>'setiausaha sulit kepada yab ketua menteri'],
            ['name'=>'PEMBANTU OPERASI KANAN','description'=>'pembantu operasi kanan'],
            ['name'=>'SETIAUSAHA AKHBAR KEPADA YAB KETUA MENTERI MELAKA','description'=>'setiausaha akhbar kepada yab ketua menteri melaka'],
            ['name'=>'PEMBANTU SETIAUSAHA PEJABAT','description'=>'pembantu setiausaha pejabat'],
        ];
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }
}

